name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm recursive install

      - name: Build
        run: pnpm run --filter template build:gh

      - name: Generate index
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: cd ./.github && sudo ./generate_index.sh -r "$GITHUB_REPOSITORY"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          force_orphan: true
          commit_message: ${{ github.event.head_commit.message }}